name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - 'README.md'
    - 'docs/*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 26.1
          - 26.3
          - 27.1
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: actions/checkout@v2
    - uses: leotaku/elisp-check@master
      with:
        file: 'telega.el'
        ignore_warnings: true
    - name: Byte Compile
      run: make compile
